[package]
name = "mini_db"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
fs-err = "3.1.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"

[dev-dependencies]
tempfile = "3.23.0"
